apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          image: hashicorp/http-echo:latest
          args:
            - -text=Hello from KubeApp backend! Running on Kubernetes via ArgoCD.
            - -listen=:5678
          ports:
            - containerPort: 5678

