apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hashicorp/http-echo:latest
          args:
            - -text=Hello from KubeApp backend! Running on Kubernetes via ArgoCD.
            - -listen=:5678
          ports:
            - containerPort: 5678
